// Vulnerability Ids

const vulnerabilities = {
  AUTH_THROUGH_TX_ORIGIN: 'AUTH_THROUGH_TX_ORIGIN',
  FLOATING_PRAGMA: 'FLOATING_PRAGMA',
  HARDCODED_GAS_AMOUNT: 'HARDCODED_GAS_AMOUNT',
  INT_OVERFLOW: 'INT_OVERFLOW',
  INT_UNDERFLOW: 'INT_UNDERFLOW',
  OUTDATED_COMPILER_VERSION: 'OUTDATED_COMPILER_VERSION',
  REENTRANCY: 'REENTRANCY',
  UNCHECKED_CALL_RETURN_VALUE: 'UNCHECKED_CALL_RETURN_VALUE'
}

module.exports = { vulnerabilities }
